name: my dvc lab 
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ordinal-nucleus-353010
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install 'dvc[gs]'
          dvc pull 
          pip install -r requirments.txt
          python train.py

          cat metrics.txt >> report.md
          cml publish plot.png --md >> report.md
          cml send-comment report.md
